### ISSUE TITLE
Difference between sum of squares and square of sums of first one hundred natural number

### ISSUE THREAD

**Issue by aosalaudeen951** [ChrisEngstrom/Project-Euler-Problem-6#1]
I solved the problem with the code below:

def ListofNaturalnumbers(n):
	i =1
	Listofnumbers=[]
	while i <= n:
		Listofnumbers.append(i)
		i+=1
	return (Listofnumbers)
	
def Squareofsums(n):
	Total = 0
	Naturalnumbers = ListofNaturalnumbers (n)
	for i in Naturalnumbers:
		Total+=i
	return (Total**2)

def Sumofsquares(n):
	Naturalnumbers = ListofNaturalnumbers (n)
	Listofsquares=[]
	for i in Naturalnumbers:
		d = i**2
		Listofsquares.append(d)
	return sum(Listofsquares)
print("List of first 100 Natural Numbers = ",ListofNaturalnumbers(100))
print ("Sum of squares of first 100 natural numbers = ", Sumofsquares(100))
print("Square of the sum of first 100 natural numbers = ", Squareofsums(100))
print("Difference between the sum of squares of first 100 Natural Numbers and the square of the sum of first 100 Natural Numbers = ", Squareofsums(100) -  Sumofsquares(100))@ChrisEngstrom

**Comment by aosalaudeen951** [comment]
As a newbie in coding. I see this as a starting point

**Comment by ChrisEngstrom** [comment]
@aosalaudeen951 

Very cool and good start! The couple of things I would say is to use variables to hold the results of your functions at the end so you don't have to compute them multiple times, specifically the two used in the final print statement. Also, it seems like you are adding the two together in the last print statement using a double negative, which will not give you the difference between the two.

Lastly, submitting an issue isn't the best way to share your code, which is a different solution to the problem in a different language than the repository. An issue is meant to point out a problem/error with the existing code in the repository that you are submitting it for. I would suggest creating your own repository so that you can have your solution and modify it in the future if you come up with a better way to solve it.

Keep going and keep learning! 👍
